version: '2'
services:
  homelab-app:
    image: homelab
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://homelab-mysql:3306/homelab?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://homelab-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://homelab-elasticsearch:9200
    ports:
      - 8080:8080
  homelab-mysql:
    extends:
      file: mysql.yml
      service: homelab-mysql
  homelab-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: homelab-elasticsearch
